# Generated by Django 6.0.2 on 2026-02-13 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('COMPUTADOR', 'Computador/Notebook'), ('SERVIDOR', 'Servidor'), ('REDE', 'Rede (Switch/Router/Modem)'), ('IMPRESSORA', 'Impressora'), ('MONITOR', 'Monitor'), ('PERIFERICO', 'Periférico/Outro')], max_length=20)),
                ('marca_modelo', models.CharField(blank=True, max_length=100)),
                ('codigo_identificacao', models.CharField(blank=True, db_index=True, editable=False, max_length=6, null=True, unique=True)),
                ('numero_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Observações / Descrição')),
                ('processador', models.CharField(blank=True, max_length=100)),
                ('memoria_ram', models.CharField(blank=True, max_length=50)),
                ('armazenamento', models.CharField(blank=True, max_length=100)),
                ('sistema_operacional', models.CharField(blank=True, max_length=50)),
                ('anydesk_id', models.CharField(blank=True, max_length=50)),
                ('usuario_local', models.CharField(blank=True, max_length=50)),
                ('senha_local', models.CharField(blank=True, max_length=100)),
                ('ip_local', models.CharField(blank=True, max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Ativo/Hardware',
                'verbose_name_plural': 'Ativos',
                'db_table': 'TB_ATIVO',
                'ordering': ['nome'],
            },
        ),
    ]
