# Generated by Django 6.0.1 on 2026-02-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações / Descrição'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='numero_serial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série / Service Tag'),
        ),
    ]
