# Generated by Django 6.0.2 on 2026-02-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_ativo_descricao_ativo_numero_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='numero_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
