# Generated by Django 6.0.2 on 2026-02-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0003_alter_ativo_numero_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='codigo_identificacao',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=6, null=True, unique=True),
        ),
    ]
