# Generated by Django 6.0.2 on 2026-02-13 00:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
        ('equipe', '0001_initial'),
        ('estoque', '0001_initial'),
        ('infra', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('VISITA', 'Visita Técnica'), ('CHURN', 'Risco de Cancelamento'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TB_NOTIFICACAO',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(help_text='Ex: Formatação PC, Instalação Câmeras', max_length=150)),
                ('tipo', models.CharField(choices=[('LABORATORIO', 'Laboratório (Interno)'), ('EXTERNO', 'Projeto Externo / Visita'), ('REMOTO', 'Acesso Remoto Especializado')], default='LABORATORIO', max_length=20)),
                ('status', models.CharField(choices=[('ORCAMENTO', 'Orçamento'), ('APROVADO', 'Aprovado'), ('EM_EXECUCAO', 'Em Execução'), ('AGUARDANDO_PECA', 'Aguardando Peça'), ('CONCLUIDO', 'Concluído'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ORCAMENTO', max_length=20)),
                ('descricao_problema', models.TextField(verbose_name='Descrição do Pedido/Problema')),
                ('relatorio_tecnico', models.TextField(blank=True, verbose_name='Laudo Técnico / Solução')),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_previsao', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('custo_deslocamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('custo_terceiros', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_mao_de_obra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_os', to='infra.ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='clientes.cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='core.empresa')),
                ('tecnico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos_liderados', to='equipe.equipe')),
                ('tecnicos', models.ManyToManyField(blank=True, related_name='servicos_participante', to='equipe.equipe')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'db_table': 'TB_ORDEM_SERVICO',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_venda', models.DecimalField(decimal_places=2, help_text='Preço cobrado no momento da OS', max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='servicos.ordemservico')),
            ],
            options={
                'verbose_name': 'Peça Utilizada',
                'db_table': 'TB_ITEM_SERVICO',
            },
        ),
        migrations.CreateModel(
            name='AnexoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='servicos_docs/%Y/%m/')),
                ('tipo', models.CharField(choices=[('NF', 'Nota Fiscal'), ('ORCAMENTO', 'Orçamento PDF'), ('LAUDO', 'Laudo Técnico'), ('FOTO', 'Foto / Evidência'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='servicos.ordemservico')),
            ],
            options={
                'db_table': 'TB_ANEXO_SERVICO',
            },
        ),
    ]
