# Generated by Django 6.0.2 on 2026-02-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='ativo',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='ativos',
            field=models.ManyToManyField(blank=True, related_name='historico_os', to='infra.ativo'),
        ),
    ]
