# Generated by Django 6.0.2 on 2026-02-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
        ('servicos', '0002_ordemservico_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='tecnicos',
            field=models.ManyToManyField(blank=True, related_name='servicos_participante', to='equipe.equipe'),
        ),
    ]
