# Generated by Django 6.0.2 on 2026-02-15 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicos', '0003_comentarioordemservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_solicitados', to='clientes.contatocliente', verbose_name='Solicitante'),
        ),
    ]
