# Generated by Django 6.0.2 on 2026-02-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_ordemservico_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='arquivo_orcamento',
            field=models.FileField(blank=True, null=True, upload_to='servicos/orcamentos/'),
        ),
    ]
