# Generated by Django 6.0.3 on 2026-03-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_ordemservico_arquivo_orcamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
