# Generated by Django 6.0.2 on 2026-02-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_fornecedor_empresa_movimentacaoestoque_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação/Motivo'),
        ),
    ]
