# Generated by Django 6.0.1 on 2026-01-23 00:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('equipe', '0001_initial'),
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao_detalhada', models.TextField(max_length=500)),
                ('origem', models.CharField(default='TELEFONE', max_length=50)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('AGENDADO', 'Agendado (Visita)')], default='ABERTO', max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20)),
                ('tipo_atendimento', models.CharField(choices=[('REMOTO', 'Acesso Remoto'), ('VISITA', 'Visita Técnica'), ('LABORATORIO', 'Laboratório Interno')], default='REMOTO', max_length=20)),
                ('data_agendamento', models.DateTimeField(blank=True, null=True)),
                ('custo_ida', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('custo_volta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('custo_transporte', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('protocolo', models.CharField(blank=True, max_length=30, unique=True)),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.ForeignKey(blank=True, help_text='Equipamento que recebeu o serviço', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_servicos', to='infra.ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
            options={
                'db_table': 'TB_CHAMADO',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChamadoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipe.equipe')),
            ],
            options={
                'db_table': 'TB_CHAMADO_TECNICO',
                'unique_together': {('chamado', 'tecnico')},
            },
        ),
        migrations.AddField(
            model_name='chamado',
            name='tecnicos',
            field=models.ManyToManyField(through='chamados.ChamadoTecnico', to='equipe.equipe'),
        ),
        migrations.CreateModel(
            name='ApontamentoHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_gastas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao_tecnica', models.CharField(max_length=255)),
                ('data_apontamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('chamado_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='chamados.chamadotecnico')),
            ],
            options={
                'db_table': 'TB_APONTAMENTO_HORAS',
            },
        ),
        migrations.CreateModel(
            name='EquipamentoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('defeito_relatado', models.TextField(max_length=500)),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('data_prevista_entrega', models.DateField()),
                ('chamado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipamento_laboratorio', to='chamados.chamado')),
            ],
            options={
                'db_table': 'TB_EQUIPAMENTO_ENTRADA',
            },
        ),
    ]
