# Generated by Django 6.0.2 on 2026-02-13 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssuntoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assunto de Chamado',
                'verbose_name_plural': 'Assuntos de Chamados',
                'db_table': 'TB_ASSUNTO_CHAMADO',
                'ordering': ['titulo'],
            },
        ),
        migrations.AddField(
            model_name='chamado',
            name='assunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chamados.assuntochamado'),
        ),
    ]
