# Generated by Django 6.0.1 on 2026-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='financeiro_gerado',
            field=models.BooleanField(default=False, help_text='Indica se a cobrança automática foi gerada'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='valor_servico',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Serviço (Avulso)'),
        ),
    ]
