# Generated by Django 6.0.2 on 2026-02-15 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_assuntochamado_chamado_assunto'),
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipe.equipe')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='chamados.chamado')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
