# Generated by Django 6.0.1 on 2026-01-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_chamado_financeiro_gerado_chamado_valor_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='arquivo_conclusao',
            field=models.FileField(blank=True, help_text='Comprovante ou OS assinada anexada pelo técnico na finalização', null=True, upload_to='chamados/conclusao/%Y/%m/'),
        ),
    ]
