# Generated by Django 6.0.2 on 2026-02-15 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_comentariochamado'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_solicitados', to='clientes.contatocliente', verbose_name='Solicitante'),
        ),
    ]
