# Generated by Django 6.0.1 on 2026-02-03 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_chamado_arquivo_conclusao'),
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='arquivo_1',
            field=models.FileField(blank=True, null=True, upload_to='chamados/docs/'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='arquivo_2',
            field=models.FileField(blank=True, null=True, upload_to='chamados/docs/'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='chamados/fotos/'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='foto_depois',
            field=models.ImageField(blank=True, null=True, upload_to='chamados/fotos/'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='resolucao',
            field=models.TextField(blank=True, null=True, verbose_name='Resolução Técnica'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_responsavel', to='equipe.equipe', verbose_name='Técnico Responsável'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='arquivo_conclusao',
            field=models.FileField(blank=True, null=True, upload_to='chamados/conclusao/%Y/%m/'),
        ),
    ]
