# Generated by Django 6.0.2 on 2026-03-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_chamado_solicitante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='assunto',
        ),
        migrations.AddField(
            model_name='chamado',
            name='assuntos',
            field=models.ManyToManyField(blank=True, related_name='chamados', to='chamados.assuntochamado'),
        ),
    ]
