# Generated by Django 6.0.2 on 2026-02-05 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_chamado_arquivo_1_chamado_arquivo_2_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='core.empresa', verbose_name='Filial/Empresa'),
        ),
    ]
