# Generated by Django 6.0.2 on 2026-03-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_remove_chamado_assunto_chamado_assuntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
