# Generated by Django 6.0.2 on 2026-02-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_chamado_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='origem',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('TELEFONE', 'Telefone'), ('SISTEMA', 'Sistema'), ('OUTRO', 'Outro')], default='TELEFONE', max_length=50),
        ),
    ]
