# Generated by Django 6.0.3 on 2026-03-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_alter_chamado_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolucaoAssunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resolucao', models.TextField(verbose_name='Resolução do Assunto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.assuntochamado')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolucoes_assuntos', to='chamados.chamado')),
            ],
            options={
                'db_table': 'TB_RESOLUCAO_ASSUNTO',
                'unique_together': {('chamado', 'assunto')},
            },
        ),
    ]
