# Generated by Django 6.0.3 on 2026-03-11 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0007_resolucaoassunto'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='custo_terceiros',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chamado',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='data_previsao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chamado',
            name='relatorio_tecnico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='valor_mao_de_obra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ORCAMENTO', 'Orçamento'), ('APROVADO', 'Aprovado'), ('AGENDADO', 'Agendado (Visita)'), ('EM_ANDAMENTO', 'Em Andamento / Execução'), ('AGUARDANDO_PECA', 'Aguardando Peça'), ('FINALIZADO', 'Finalizado / Concluído'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=20),
        ),
        migrations.CreateModel(
            name='AnexoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='chamados_docs/%Y/%m/')),
                ('tipo', models.CharField(choices=[('NF', 'Nota Fiscal'), ('ORCAMENTO', 'Orçamento PDF'), ('LAUDO', 'Laudo Técnico'), ('FOTO', 'Foto / Evidência'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_os', to='chamados.chamado')),
            ],
            options={
                'db_table': 'TB_ANEXO_CHAMADO',
            },
        ),
        migrations.CreateModel(
            name='ItemChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_venda', models.DecimalField(decimal_places=2, help_text='Preço cobrado no momento do Chamado', max_digits=10)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='chamados.chamado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Peça Utilizada (Chamado)',
                'db_table': 'TB_ITEM_CHAMADO',
            },
        ),
    ]
