# Generated by Django 6.0.1 on 2026-01-23 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razao_social', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('endereco', models.CharField(max_length=150)),
                ('valor_contrato_mensal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10)),
                ('tipo_cliente', models.CharField(choices=[('CONTRATO', 'Contrato'), ('AVULSO', 'Avulso')], default='AVULSO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'TB_CLIENTE',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='ContaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
                ('nome_usuario', models.CharField(blank=True, max_length=100)),
                ('provedor', models.CharField(default='Locaweb', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_email', to='clientes.cliente')),
            ],
            options={
                'db_table': 'TB_CONTA_EMAIL',
            },
        ),
        migrations.CreateModel(
            name='ContatoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_principal', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contato do Cliente',
                'db_table': 'TB_CONTATO_CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='ContratoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='contratos/%Y/%m/')),
                ('descricao', models.CharField(max_length=200)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'TB_CONTRATO_CLIENTE',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='DocumentacaoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuracao_mikrotik', models.TextField(blank=True, default='')),
                ('topologia_rede', models.TextField(blank=True, default='')),
                ('estrutura_servidores', models.TextField(blank=True, default='')),
                ('rotina_backup', models.TextField(blank=True, default='')),
                ('pontos_fracos_melhorias', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentacao_tecnica', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Documentação Técnica',
                'db_table': 'TB_DOCUMENTACAO_TECNICA',
            },
        ),
        migrations.CreateModel(
            name='ProvedorInternet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_operadora', models.CharField(max_length=50)),
                ('plano_contratado', models.CharField(blank=True, max_length=100)),
                ('ip_fixo', models.CharField(blank=True, max_length=50)),
                ('telefone_suporte', models.CharField(blank=True, max_length=20)),
                ('usuario_pppoe', models.CharField(blank=True, max_length=100)),
                ('senha_pppoe', models.CharField(blank=True, max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provedores', to='clientes.cliente')),
            ],
            options={
                'db_table': 'TB_PROVEDOR_INTERNET',
            },
        ),
    ]
