# Generated by Django 6.0.2 on 2026-02-15 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('receber_alertas', models.BooleanField(default=True, help_text='Habilita disparo de PDFs/Relatórios automáticos')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_gestao', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'E-mail de Gestão',
                'db_table': 'TB_EMAIL_GESTAO',
            },
        ),
    ]
