# Generated by Django 6.0.2 on 2026-02-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('BOLETO', 'Boleto')], default='DINHEIRO', max_length=20),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_entrada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
