# Generated by Django 6.0.2 on 2026-02-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_forma_pagamento_venda_valor_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='vincular_contrato',
            field=models.BooleanField(default=False),
        ),
    ]
