# Generated by Django 6.0.2 on 2026-02-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_venda_vincular_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='arquivo_orcamento',
            field=models.FileField(blank=True, null=True, upload_to='orcamentos_vendas/'),
        ),
        migrations.AddField(
            model_name='venda',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_vendas/'),
        ),
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('ORCAMENTO', 'Orçamento'), ('CONCLUIDA', 'Concluída'), ('REVOGADA', 'Revogada')], default='ORCAMENTO', max_length=20),
        ),
        migrations.AddField(
            model_name='venda',
            name='validade_orcamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
