# Generated by Django 5.0.2 on 2026-02-16 18:40

from django.db import migrations

def set_existing_sales_to_concluida(apps, schema_editor):
    Venda = apps.get_model('vendas', 'Venda')
    # This will find all sales that are currently quotes and have no expiration date,
    # which is a good proxy for sales that existed before the status system was added.
    Venda.objects.filter(status='ORCAMENTO', validade_orcamento__isnull=True).update(status='CONCLUIDA')

class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_venda_arquivo_orcamento_venda_comprovante_pagamento_and_more'),
    ]

    operations = [
        migrations.RunPython(set_existing_sales_to_concluida),
    ]
