# Generated by Django 6.0.2 on 2026-02-17 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_emailgestao'),
        ('vendas', '0006_remove_venda_preco_unitario_remove_venda_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='clientes.contatocliente'),
        ),
    ]
