# Generated by Django 6.0.3 on 2026-03-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_venda_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('ORCAMENTO', 'Orçamento'), ('CONCLUIDA', 'Concluída (Aprovada)'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido')], default='ORCAMENTO', max_length=20),
        ),
    ]
