# Generated by Django 6.0.2 on 2026-02-13 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
        ('equipe', '0001_initial'),
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('CONTRATO', 'Mensalidade de Contrato'), ('VENDA', 'Venda de Hardware'), ('SERVICO', 'Serviço Avulso'), ('TRANSPORTE', 'Transporte / Deslocamento'), ('CUSTO_TEC', 'Custo Operacional Técnico'), ('DESPESA', 'Despesa Administrativa'), ('COMPRA', 'Compra de Estoque'), ('SALARIO', 'Salário/Pessoal'), ('IMPOSTO', 'Impostos'), ('OUTRO', 'Outro')], default='DESPESA', max_length=20)),
                ('dia_vencimento', models.IntegerField(help_text='Dia do mês que vence (1-31)')),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_geracao', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'db_table': 'TB_DESPESA_RECORRENTE',
            },
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('tipo_lancamento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=20)),
                ('categoria', models.CharField(choices=[('CONTRATO', 'Mensalidade de Contrato'), ('VENDA', 'Venda de Hardware'), ('SERVICO', 'Serviço Avulso'), ('TRANSPORTE', 'Transporte / Deslocamento'), ('CUSTO_TEC', 'Custo Operacional Técnico'), ('DESPESA', 'Despesa Administrativa'), ('COMPRA', 'Compra de Estoque'), ('SALARIO', 'Salário/Pessoal'), ('IMPOSTO', 'Impostos'), ('OUTRO', 'Outro')], default='DESPESA', max_length=20)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('arquivo_1', models.FileField(blank=True, null=True, upload_to='financeiro/comprovantes/%Y/%m/')),
                ('arquivo_2', models.FileField(blank=True, null=True, upload_to='financeiro/comprovantes/%Y/%m/')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='financeiro/comprovantes/%Y/%m/')),
                ('forma_pagamento', models.CharField(choices=[('BOLETO', 'Boleto'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência')], default='DINHEIRO', max_length=20)),
                ('parcela_atual', models.IntegerField(default=1)),
                ('total_parcelas', models.IntegerField(default=1)),
                ('grupo_parcelamento', models.UUIDField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='core.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='estoque.fornecedor')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipe.equipe')),
            ],
            options={
                'verbose_name': 'Lançamento Financeiro',
                'db_table': 'TB_LANCAMENTO_FINANCEIRO',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='FechamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('fechado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TB_FECHAMENTO_FINANCEIRO',
                'unique_together': {('ano', 'mes', 'empresa')},
            },
        ),
    ]
