# Generated by Django 6.0.1 on 2026-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='financeiro/comprovantes/%Y/%m/'),
        ),
    ]
