# Generated by Django 6.0.1 on 2026-02-03 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('financeiro', '0002_lancamentofinanceiro_comprovante'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fechamentofinanceiro',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='despesarecorrente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='fechamentofinanceiro',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='despesarecorrente',
            name='ultima_geracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='grupo_parcelamento',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='fechamentofinanceiro',
            unique_together={('ano', 'mes', 'empresa')},
        ),
    ]
