# Generated by Django 6.0.2 on 2026-02-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_fechamentofinanceiro_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesarecorrente',
            name='categoria',
            field=models.CharField(choices=[('CONTRATO', 'Mensalidade de Contrato'), ('VENDA', 'Venda de Hardware'), ('SERVICO', 'Serviço Avulso'), ('TRANSPORTE', 'Transporte / Deslocamento'), ('CUSTO_TEC', 'Custo Operacional Técnico'), ('DESPESA', 'Despesa Administrativa'), ('COMPRA', 'Compra de Estoque'), ('SALARIO', 'Salário/Pessoal'), ('IMPOSTO', 'Impostos'), ('OUTRO', 'Outro')], default='DESPESA', max_length=20),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='categoria',
            field=models.CharField(choices=[('CONTRATO', 'Mensalidade de Contrato'), ('VENDA', 'Venda de Hardware'), ('SERVICO', 'Serviço Avulso'), ('TRANSPORTE', 'Transporte / Deslocamento'), ('CUSTO_TEC', 'Custo Operacional Técnico'), ('DESPESA', 'Despesa Administrativa'), ('COMPRA', 'Compra de Estoque'), ('SALARIO', 'Salário/Pessoal'), ('IMPOSTO', 'Impostos'), ('OUTRO', 'Outro')], default='DESPESA', max_length=20),
        ),
    ]
