# Generated by Django 6.0 on 2026-01-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('endereco', models.CharField(max_length=150)),
                ('valor_contrato_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_vencimento', models.PositiveSmallIntegerField()),
                ('tipo_cliente', models.CharField(choices=[('CONTRATO', 'Contrato'), ('AVULSO', 'Avulso')], default='AVULSO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'TB_CLIENTE',
            },
        ),
    ]
