# Generated by Django 6.0.2 on 2026-02-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('eh_matriz', models.BooleanField(default=False, verbose_name='É a Matriz?')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/')),
                ('cor_primaria', models.CharField(default='#302464', help_text='Cor HEX (ex: #302464)', max_length=7)),
                ('cor_secundaria', models.CharField(default='#7C69AF', help_text='Cor HEX Secundária', max_length=7)),
                ('banco_nome', models.CharField(blank=True, max_length=50)),
                ('agencia', models.CharField(blank=True, max_length=20)),
                ('conta', models.CharField(blank=True, max_length=20)),
                ('chave_pix', models.CharField(blank=True, max_length=100)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa / Filial',
                'verbose_name_plural': 'Empresas / Filiais',
            },
        ),
    ]
