# Generated by Django 6.0 on 2026-01-03 22:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('custo_hora', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'TB_EQUIPE',
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('CONTRATO', 'Contrato'), ('AVULSO', 'Avulso')], max_length=20),
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_maquina', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('dados_acesso', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='ativos', to='core.cliente')),
            ],
            options={
                'db_table': 'TB_ATIVO',
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao_detalhada', models.TextField(max_length=500)),
                ('origem', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20)),
                ('protocolo', models.CharField(max_length=30, unique=True)),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
            ],
            options={
                'db_table': 'TB_CHAMADO',
            },
        ),
        migrations.CreateModel(
            name='ChamadoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('chamado', models.ForeignKey(db_column='id_chamado', on_delete=django.db.models.deletion.CASCADE, to='core.chamado')),
                ('tecnico', models.ForeignKey(db_column='id_tecnico', on_delete=django.db.models.deletion.PROTECT, to='core.equipe')),
            ],
            options={
                'db_table': 'TB_CHAMADO_TECNICO',
                'unique_together': {('chamado', 'tecnico')},
            },
        ),
        migrations.CreateModel(
            name='ApontamentoHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_gastas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao_tecnica', models.CharField(max_length=255)),
                ('data_apontamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('chamado_tecnico', models.ForeignKey(db_column='id_chamado_tecnico', on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='core.chamadotecnico')),
            ],
            options={
                'db_table': 'TB_APONTAMENTO_HORAS',
            },
        ),
        migrations.CreateModel(
            name='EquipamentoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('acessorios', models.CharField(blank=True, max_length=150, null=True)),
                ('estado_conservacao', models.CharField(blank=True, max_length=100, null=True)),
                ('defeito_relatado', models.TextField(max_length=500)),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('data_prevista_entrega', models.DateField()),
                ('relatorio_tecnico', models.TextField(blank=True, max_length=500, null=True)),
                ('chamado', models.OneToOneField(db_column='id_chamado', on_delete=django.db.models.deletion.CASCADE, related_name='equipamento_laboratorio', to='core.chamado')),
            ],
            options={
                'db_table': 'TB_EQUIPAMENTO_ENTRADA',
            },
        ),
        migrations.AddField(
            model_name='chamado',
            name='tecnicos',
            field=models.ManyToManyField(through='core.ChamadoTecnico', to='core.equipe'),
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('tipo_lancamento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=20)),
                ('data_vencimento', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'db_table': 'TB_LANCAMENTO_FINANCEIRO',
            },
        ),
    ]
