# Generated by Django 6.0.2 on 2026-02-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='eh_matriz',
            field=models.BooleanField(default=False, verbose_name='É a Matriz?'),
        ),
    ]
