# Generated by Django 6.0 on 2026-01-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipe_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apontamentohoras',
            options={'verbose_name': 'Apontamento de Horas', 'verbose_name_plural': 'Apontamentos de Horas'},
        ),
        migrations.AlterModelOptions(
            name='chamadotecnico',
            options={'verbose_name': 'Técnico no Chamado', 'verbose_name_plural': 'Técnicos nos Chamados'},
        ),
        migrations.AlterModelOptions(
            name='equipamentoentrada',
            options={'verbose_name': 'Entrada de Equipamento', 'verbose_name_plural': 'Entradas de Equipamentos'},
        ),
        migrations.AlterField(
            model_name='chamado',
            name='protocolo',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
