# Generated by Django 6.0 on 2026-01-06 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_equipe_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apontamentohoras',
            options={},
        ),
        migrations.AlterModelOptions(
            name='chamadotecnico',
            options={},
        ),
        migrations.AlterModelOptions(
            name='equipamentoentrada',
            options={},
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='dados_acesso',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='nome_maquina',
        ),
        migrations.AddField(
            model_name='ativo',
            name='anydesk_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ativo',
            name='armazenamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ativo',
            name='ip_local',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ativo',
            name='marca_modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ativo',
            name='memoria_ram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ativo',
            name='nome',
            field=models.CharField(default='DESCONHECIDO', help_text='Hostname ou Nome do dispositivo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ativo',
            name='processador',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ativo',
            name='senha_local',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ativo',
            name='sistema_operacional',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ativo',
            name='usuario_local',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='tipo',
            field=models.CharField(choices=[('COMPUTADOR', 'Computador/Notebook'), ('SERVIDOR', 'Servidor'), ('REDE', 'Rede (Switch/Router/Modem)'), ('IMPRESSORA', 'Impressora'), ('MONITOR', 'Monitor'), ('PERIFERICO', 'Periférico/Outro')], max_length=20),
        ),
        migrations.CreateModel(
            name='ContaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
                ('nome_usuario', models.CharField(blank=True, help_text='Nome de quem usa', max_length=100)),
                ('provedor', models.CharField(default='Locaweb', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_email', to='core.cliente')),
            ],
            options={
                'db_table': 'TB_CONTA_EMAIL',
            },
        ),
        migrations.CreateModel(
            name='ContatoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_principal', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='core.cliente')),
            ],
            options={
                'db_table': 'TB_CONTATO_CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='DocumentacaoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuracao_mikrotik', models.TextField(blank=True, help_text='Scripts, regras de firewall e rotas')),
                ('estrutura_servidores', models.TextField(blank=True, help_text='Descrição do AD, DNS, DHCP, funções dos servidores')),
                ('topologia_rede', models.TextField(blank=True, help_text='Descrição física da rede, cascateamento, VLANs')),
                ('rotina_backup', models.TextField(blank=True, help_text='Como é feito o backup e onde é salvo')),
                ('pontos_fracos_melhorias', models.TextField(blank=True, help_text='Relatório de gargalos e sugestões de upgrade')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentacao_tecnica', to='core.cliente')),
            ],
            options={
                'db_table': 'TB_DOCUMENTACAO_TECNICA',
            },
        ),
        migrations.CreateModel(
            name='ProvedorInternet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_operadora', models.CharField(max_length=50)),
                ('plano_contratado', models.CharField(blank=True, max_length=100)),
                ('ip_fixo', models.CharField(blank=True, help_text='IP Estático se houver', max_length=50)),
                ('telefone_suporte', models.CharField(blank=True, max_length=20)),
                ('usuario_pppoe', models.CharField(blank=True, max_length=100)),
                ('senha_pppoe', models.CharField(blank=True, max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provedores', to='core.cliente')),
            ],
            options={
                'db_table': 'TB_PROVEDOR_INTERNET',
            },
        ),
    ]
