# Generated by Django 6.0 on 2026-01-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_apontamentohoras_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='custo_transporte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chamado',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='tipo_atendimento',
            field=models.CharField(choices=[('REMOTO', 'Acesso Remoto'), ('VISITA', 'Visita Técnica'), ('LABORATORIO', 'Laboratório Interno')], default='REMOTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('AGENDADO', 'Agendado (Visita)')], default='ABERTO', max_length=20),
        ),
    ]
