# Generated by Django 6.0 on 2026-01-09 01:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chamado_custo_transporte_chamado_data_agendamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('contato_nome', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'TB_FORNECEDOR',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('HARDWARE', 'Hardware (Peças)'), ('REDES', 'Redes (Cabos/Conectores)'), ('PERIFERICO', 'Periférico'), ('SOFTWARE', 'Software/Licença'), ('OUTROS', 'Outros')], max_length=20)),
                ('estoque_minimo', models.PositiveIntegerField(default=2, help_text='Avisar quando chegar neste nível')),
                ('controlar_serial', models.BooleanField(default=False, help_text='Exige Serial Number na saída?')),
                ('preco_venda_sugerido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'TB_PRODUTO',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Devolução)'), ('SAIDA', 'Saída (Venda/Uso)')], max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Custo na Entrada ou Venda na Saída', max_digits=10)),
                ('data_movimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_serial', models.CharField(blank=True, help_text='S/N da peça específica', max_length=100, null=True)),
                ('chamado', models.ForeignKey(blank=True, help_text='Se for usado em serviço', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chamado')),
                ('fornecedor', models.ForeignKey(blank=True, help_text='Se for Entrada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='core.produto')),
            ],
            options={
                'db_table': 'TB_MOVIMENTACAO_ESTOQUE',
            },
        ),
    ]
