# Generated by Django 6.0 on 2026-01-09 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fornecedor_produto_movimentacaoestoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='chamado',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='usuario',
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='docs_estoque/'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='data_movimento',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='numero_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo_movimento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='movimentacaoestoque',
            table=None,
        ),
    ]
