# Generated by Django 6.0.1 on 2026-01-10 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_movimentacaoestoque_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamentofinanceiro',
            options={'ordering': ['-data_vencimento'], 'verbose_name': 'Lançamento Financeiro', 'verbose_name_plural': 'Lançamentos Financeiros'},
        ),
        migrations.RenameField(
            model_name='lancamentofinanceiro',
            old_name='created_at',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='categoria',
            field=models.CharField(choices=[('CONTRATO', 'Mensalidade de Contrato'), ('VENDA', 'Venda de Hardware'), ('SERVICO', 'Serviço Avulso'), ('CUSTO_TEC', 'Custo Operacional Técnico'), ('DESPESA', 'Despesa Administrativa'), ('COMPRA', 'Compra de Estoque')], default='DESPESA', max_length=20),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_gerados', to='core.equipe'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financeiro', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago / Recebido'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='tipo_lancamento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (+Recursos)'), ('SAIDA', 'Saída (-Despesas)')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='lancamentofinanceiro',
            table=None,
        ),
    ]
