# Generated by Django 6.0.1 on 2026-01-10 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_lancamentofinanceiro_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamentofinanceiro',
            options={},
        ),
        migrations.RenameField(
            model_name='lancamentofinanceiro',
            old_name='data_criacao',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='descricao',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='tipo_lancamento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='lancamentofinanceiro',
            table='TB_LANCAMENTO_FINANCEIRO',
        ),
    ]
