# Generated by Django 6.0.1 on 2026-01-10 21:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fechamentofinanceiro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechamentofinanceiro',
            options={},
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='custo_transporte',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='equipamentoentrada',
            name='acessorios',
        ),
        migrations.RemoveField(
            model_name='equipamentoentrada',
            name='estado_conservacao',
        ),
        migrations.RemoveField(
            model_name='equipamentoentrada',
            name='relatorio_tecnico',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='contato_nome',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='site',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='numero_serial',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='controlar_serial',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.AddField(
            model_name='documentacaotecnica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apontamentohoras',
            name='chamado_tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='core.chamadotecnico'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='chamadotecnico',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chamado'),
        ),
        migrations.AlterField(
            model_name='chamadotecnico',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.equipe'),
        ),
        migrations.AlterField(
            model_name='contaemail',
            name='nome_usuario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='documentacaotecnica',
            name='configuracao_mikrotik',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentacaotecnica',
            name='estrutura_servidores',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentacaotecnica',
            name='pontos_fracos_melhorias',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentacaotecnica',
            name='rotina_backup',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentacaotecnica',
            name='topologia_rede',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipamentoentrada',
            name='chamado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipamento_laboratorio', to='core.chamado'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='categoria',
            field=models.CharField(choices=[('CONTRATO', 'Mensalidade'), ('VENDA', 'Venda de Hardware'), ('SERVICO', 'Serviço Avulso'), ('DESPESA', 'Despesa Administrativa')], default='DESPESA', max_length=20),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.equipe'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='provedorinternet',
            name='ip_fixo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterModelTable(
            name='movimentacaoestoque',
            table='TB_MOVIMENTACAO_ESTOQUE',
        ),
    ]
