# Generated by Django 6.0.1 on 2026-01-10 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_fechamentofinanceiro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='docs_estoque/'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='numero_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
