# Generated by Django 6.0.1 on 2026-01-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_movimentacaoestoque_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='categoria',
            field=models.CharField(choices=[('CONTRATO', 'Mensalidade de Contrato'), ('VENDA', 'Venda de Hardware'), ('SERVICO', 'Serviço Avulso'), ('CUSTO_TEC', 'Custo Operacional Técnico'), ('DESPESA', 'Despesa Administrativa'), ('COMPRA', 'Compra de Estoque')], default='DESPESA', max_length=20),
        ),
    ]
