# Generated by Django 6.0.1 on 2026-01-10 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_lancamentofinanceiro_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ativo',
            options={'ordering': ['nome'], 'verbose_name': 'Ativo/Hardware'},
        ),
        migrations.AlterModelOptions(
            name='chamado',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['razao_social'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='contatocliente',
            options={'verbose_name': 'Contato do Cliente'},
        ),
        migrations.AlterModelOptions(
            name='equipe',
            options={'verbose_name': 'Membro da Equipe', 'verbose_name_plural': 'Equipe'},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='lancamentofinanceiro',
            options={'ordering': ['-data_vencimento'], 'verbose_name': 'Lançamento Financeiro'},
        ),
        migrations.AlterModelOptions(
            name='movimentacaoestoque',
            options={'verbose_name': 'Movimentação de Estoque'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome'], 'verbose_name': 'Produto'},
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='core.produto'),
        ),
    ]
