# Generated by Django 6.0.1 on 2026-01-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_ativo_options_alter_chamado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='contato_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
