# Generated by Django 6.0.1 on 2026-01-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_fornecedor_contato_nome_fornecedor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_equipe/'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='cargo',
            field=models.CharField(choices=[('TECNICO', 'Técnico'), ('GESTOR', 'Gestor'), ('SOCIO', 'Sócio'), ('ESTAGIARIO', 'Estagiário')], default='TECNICO', max_length=50),
        ),
    ]
