# Generated by Django 6.0.1 on 2026-01-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_equipe_foto_alter_equipe_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='custo_transporte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chamado',
            name='km_ida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chamado',
            name='km_volta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chamado',
            name='origem',
            field=models.CharField(default='TELEFONE', max_length=50),
        ),
        migrations.AddField(
            model_name='chamado',
            name='valor_km',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
        ),
    ]
