# Generated by Django 6.0.1 on 2026-01-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_chamado_custo_transporte_chamado_km_ida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='km_ida',
            new_name='custo_ida',
        ),
        migrations.RenameField(
            model_name='chamado',
            old_name='km_volta',
            new_name='custo_volta',
        ),
    ]
