# Generated by Django 6.0.1 on 2026-01-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_km_ida_chamado_custo_ida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='valor_km',
        ),
    ]
