# Generated by Django 6.0.1 on 2026-01-12 23:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_chamado_valor_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(help_text='Ex: Formatação PC, Instalação Câmeras', max_length=150)),
                ('tipo', models.CharField(choices=[('LABORATORIO', 'Laboratório (Interno)'), ('EXTERNO', 'Projeto Externo / Visita'), ('REMOTO', 'Acesso Remoto Especializado')], default='LABORATORIO', max_length=20)),
                ('status', models.CharField(choices=[('ORCAMENTO', 'Orçamento'), ('APROVADO', 'Aprovado'), ('EM_EXECUCAO', 'Em Execução'), ('AGUARDANDO_PECA', 'Aguardando Peça'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ORCAMENTO', max_length=20)),
                ('descricao_problema', models.TextField(verbose_name='Descrição do Pedido/Problema')),
                ('relatorio_tecnico', models.TextField(blank=True, verbose_name='Laudo Técnico / Solução')),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_previsao', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('custo_deslocamento', models.DecimalField(decimal_places=2, default=0.0, help_text='Uber, Combustível, Pedágio', max_digits=10)),
                ('custo_terceiros', models.DecimalField(decimal_places=2, default=0.0, help_text='Mão de obra contratada fora', max_digits=10)),
                ('valor_mao_de_obra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='core.cliente')),
                ('tecnico_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos_liderados', to='core.equipe')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'db_table': 'TB_ORDEM_SERVICO',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_venda', models.DecimalField(decimal_places=2, help_text='Preço cobrado no momento da OS', max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.ordemservico')),
            ],
            options={
                'verbose_name': 'Peça Utilizada',
                'db_table': 'TB_ITEM_SERVICO',
            },
        ),
        migrations.CreateModel(
            name='AnexoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='servicos_docs/%Y/%m/')),
                ('tipo', models.CharField(choices=[('NF', 'Nota Fiscal'), ('ORCAMENTO', 'Orçamento PDF'), ('LAUDO', 'Laudo Técnico'), ('FOTO', 'Foto / Evidência'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.ordemservico')),
            ],
            options={
                'db_table': 'TB_ANEXO_SERVICO',
            },
        ),
    ]
