# Generated by Django 6.0.1 on 2026-01-23 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_equipe/')),
                ('cargo', models.CharField(choices=[('TECNICO', 'Técnico'), ('GESTOR', 'Gestor'), ('SOCIO', 'Sócio'), ('ESTAGIARIO', 'Estagiário')], default='TECNICO', max_length=50)),
                ('custo_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Equipe',
                'db_table': 'TB_EQUIPE',
            },
        ),
    ]
